### ISSUE TITLE
Issue with gitsigns

### ISSUE THREAD

**Issue by rgnkn** [marko-cerovac/material.nvim#84] opened 2022-03-21 18:23 UTC
There is a little glitch when using `non_current_window = true` with `gitsigns.nvim`.

For the active window the signs are displayed properly. But for the inactive windows the signs get a darkened background. Is there any way to solve this issue?

I attached a screenshot where the right-most window is activated (gitsign in line 39 is fine). Please compare the gitsigns in this with the middle window (e.g. lines 22, 24, ...).

![Screenshot from 2022-03-21 19-19-18](https://user-images.githubusercontent.com/17874137/159339045-55d8b188-a270-4640-b17c-58c523e71aed.png)

**Comment by marko-cerovac** [comment] 2022-03-22 15:10
It should be fixed now. Thanks for the input and let me know if the issue is still there.

**Comment by rgnkn** [comment] 2022-03-22 17:25
Thumbs up and thx.

**Closed** 2022-03-22 17:25 UTC
